import Head from 'next/head';
import Image from 'next/image';
import DataTablest from '../component/DataTablest';
import DataTable from '../component/DataTablest';
import DataTablesTest from '../component/DataTablesTest';
import MainDataTable from '../component/MainDataTable';
import styles from '../styles/Home.module.css';
import 'bootstrap/dist/css/bootstrap.min.css';
// import 'bootstrap/dist/js/bootstrap.bundle.js';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>DXMAP</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <DataTablesTest />
        {/* <MainDataTable /> */}
      </main>

      <footer className={styles.footer}>DXMAP </footer>
    </div>
  );
}
